Vagrant.configure('2') do |config|
    # Disable /vagrant synced folder
    config.vm.synced_folder '.', '/vagrant', disabled: true

    config.vm.provider 'virtualbox' do |v|
        v.memory = 384
    end

    config.vm.define :ubuntu18 do |ubuntu|
        ubuntu.vm.box = 'bento/ubuntu-18.04'
        ubuntu.vm.network :private_network, ip: '10.42.42.25'
    end

    config.vm.define :ubuntu20 do |ubuntu|
        ubuntu.vm.box = 'bento/ubuntu-20.04'
        ubuntu.vm.network :private_network, ip: '10.42.42.26'
    end

    config.vm.define :debian9 do |debian|
        debian.vm.box = 'bento/debian-9'
        debian.vm.network :private_network, ip: '10.42.42.27'
    end

    config.vm.define :debian10 do |debian|
        debian.vm.box = 'bento/debian-10'
        debian.vm.network :private_network, ip: '10.42.42.28'
    end

    config.vm.define :centos7 do |centos|
        centos.vm.box = 'bento/centos-7'
        centos.vm.network :private_network, ip: '10.42.42.29'
    end

    config.vm.define :centos8 do |centos|
        centos.vm.box = 'bento/centos-8'
        centos.vm.network :private_network, ip: '10.42.42.30'
    end
end
